//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetterThanIMDB.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class locale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal locale() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BetterThanIMDB.Resources.locale", typeof(locale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Actors.
        /// </summary>
        internal static string actors {
            get {
                return ResourceManager.GetString("actors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Actors List.
        /// </summary>
        internal static string actorsList {
            get {
                return ResourceManager.GetString("actorsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add actor .
        /// </summary>
        internal static string addActor {
            get {
                return ResourceManager.GetString("addActor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add film .
        /// </summary>
        internal static string addFilm {
            get {
                return ResourceManager.GetString("addFilm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add genre .
        /// </summary>
        internal static string addGenre {
            get {
                return ResourceManager.GetString("addGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add producer.
        /// </summary>
        internal static string addProducer {
            get {
                return ResourceManager.GetString("addProducer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Apply Changes.
        /// </summary>
        internal static string applyChanges {
            get {
                return ResourceManager.GetString("applyChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Apply Filter.
        /// </summary>
        internal static string applyFilter {
            get {
                return ResourceManager.GetString("applyFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cast.
        /// </summary>
        internal static string cast {
            get {
                return ResourceManager.GetString("cast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Are you sure?.
        /// </summary>
        internal static string confirm {
            get {
                return ResourceManager.GetString("confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create new actor.
        /// </summary>
        internal static string createActor {
            get {
                return ResourceManager.GetString("createActor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create new movie.
        /// </summary>
        internal static string createFilm {
            get {
                return ResourceManager.GetString("createFilm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create new producer.
        /// </summary>
        internal static string createProducer {
            get {
                return ResourceManager.GetString("createProducer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Date of birth:.
        /// </summary>
        internal static string dateOfBirth {
            get {
                return ResourceManager.GetString("dateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Load images.
        /// </summary>
        internal static string downloadImages {
            get {
                return ResourceManager.GetString("downloadImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Runtime (min):.
        /// </summary>
        internal static string duration {
            get {
                return ResourceManager.GetString("duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit.
        /// </summary>
        internal static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit Actor.
        /// </summary>
        internal static string editActor {
            get {
                return ResourceManager.GetString("editActor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit Film.
        /// </summary>
        internal static string editFilm {
            get {
                return ResourceManager.GetString("editFilm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit Producer.
        /// </summary>
        internal static string editProducer {
            get {
                return ResourceManager.GetString("editProducer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Films.
        /// </summary>
        internal static string films {
            get {
                return ResourceManager.GetString("films", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Films List.
        /// </summary>
        internal static string filmsList {
            get {
                return ResourceManager.GetString("filmsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Genres.
        /// </summary>
        internal static string genres {
            get {
                return ResourceManager.GetString("genres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Genres List.
        /// </summary>
        internal static string genresList {
            get {
                return ResourceManager.GetString("genresList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Get actor from TMDB.
        /// </summary>
        internal static string getActor {
            get {
                return ResourceManager.GetString("getActor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Get movie from TMDB.
        /// </summary>
        internal static string getFilm {
            get {
                return ResourceManager.GetString("getFilm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Get producer from TMDB.
        /// </summary>
        internal static string getProducer {
            get {
                return ResourceManager.GetString("getProducer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Max Date of Birth.
        /// </summary>
        internal static string maxDate {
            get {
                return ResourceManager.GetString("maxDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Max Runtime.
        /// </summary>
        internal static string maxRuntime {
            get {
                return ResourceManager.GetString("maxRuntime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Min Date of Birth.
        /// </summary>
        internal static string minDate {
            get {
                return ResourceManager.GetString("minDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Min Runtime.
        /// </summary>
        internal static string minRuntime {
            get {
                return ResourceManager.GetString("minRuntime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No info available.
        /// </summary>
        internal static string noInfo {
            get {
                return ResourceManager.GetString("noInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Producers.
        /// </summary>
        internal static string producers {
            get {
                return ResourceManager.GetString("producers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Producers List.
        /// </summary>
        internal static string producersList {
            get {
                return ResourceManager.GetString("producersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Release date:.
        /// </summary>
        internal static string releaseDate {
            get {
                return ResourceManager.GetString("releaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove actor .
        /// </summary>
        internal static string removeActor {
            get {
                return ResourceManager.GetString("removeActor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove film .
        /// </summary>
        internal static string removeFilm {
            get {
                return ResourceManager.GetString("removeFilm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove genre.
        /// </summary>
        internal static string removeGenre {
            get {
                return ResourceManager.GetString("removeGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove producer.
        /// </summary>
        internal static string removeProducer {
            get {
                return ResourceManager.GetString("removeProducer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select Photo.
        /// </summary>
        internal static string selectPhoto {
            get {
                return ResourceManager.GetString("selectPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select Poster.
        /// </summary>
        internal static string selectPoster {
            get {
                return ResourceManager.GetString("selectPoster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на By Age.
        /// </summary>
        internal static string sortByAge {
            get {
                return ResourceManager.GetString("sortByAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на By Film`s Count.
        /// </summary>
        internal static string sortByCount {
            get {
                return ResourceManager.GetString("sortByCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на By Date.
        /// </summary>
        internal static string sortByDate {
            get {
                return ResourceManager.GetString("sortByDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на By Name.
        /// </summary>
        internal static string sortByName {
            get {
                return ResourceManager.GetString("sortByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на By Runtime.
        /// </summary>
        internal static string sortByRuntime {
            get {
                return ResourceManager.GetString("sortByRuntime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на By Title.
        /// </summary>
        internal static string sortByTitle {
            get {
                return ResourceManager.GetString("sortByTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Title.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
    }
}
